const PORTFOLIO_DATA = [
  {
    "slug": "2026-armelle",
    "type": "initiative",
    "file": "initiatives/2026-armelle.md",
    "title": "Armelle Boussidon - Onboarding & Initial Tasks",
    "description": "Initial task areas and onboarding plan for Armelle as new colleague at Life Itself.",
    "status": "active",
    "created": "Tue Mar 24 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself-management",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2rcon",
    "type": "initiative",
    "file": "initiatives/2rcon.md",
    "title": "2RCon",
    "description": "Second Renaissance related conference initiative.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "second-renaissance",
    "tags": [
      "lifeitself",
      "conference",
      "second-renaissance"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "ai-sense-making",
    "type": "initiative",
    "file": "initiatives/ai-sense-making.md",
    "title": "AI Sense-Making",
    "description": "Inquiry into the epistemic, social, and civilisational implications of AI.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "archipelago-place",
    "type": "initiative",
    "file": "initiatives/archipelago-place.md",
    "title": "Archipelago.place",
    "description": "Platform concept for mapping and connecting distributed places, hubs, and communities.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "developmental-spaces-dds",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "collective-action-course",
    "type": "initiative",
    "file": "initiatives/collective-action-course.md",
    "title": "Collective Action Course",
    "description": "Course on coordination, shared identity, and the cultural foundations of collective action.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself-courses",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "conscious-careers-guide",
    "type": "initiative",
    "file": "initiatives/conscious-careers-guide.md",
    "title": "Conscious Careers Guide",
    "description": "Life Itself related guide initiative around conscious careers.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself-courses",
    "tags": [
      "lifeitself",
      "guide",
      "careers"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "developmental-spaces-dds",
    "type": "initiative",
    "file": "initiatives/developmental-spaces-dds.md",
    "title": "Developmental Spaces (DDS)",
    "description": "Deliberately developmental / neo-monastic spaces for sustained inner and collective development.",
    "status": null,
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "farmhouse-hub",
    "type": "initiative",
    "file": "initiatives/farmhouse-hub.md",
    "title": "Farmhouse Hub",
    "description": "Ongoing maintenance and development of the farmhouse hub.",
    "status": "active",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself-hubs",
    "tags": [
      "lifeitself",
      "hubs",
      "place"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-guild",
    "type": "initiative",
    "file": "initiatives/life-guild.md",
    "title": "Life Guild",
    "description": "Life Itself sub-initiative around guild or community formation.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "community"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-courses",
    "type": "initiative",
    "file": "initiatives/life-itself-courses.md",
    "title": "Life Itself Courses",
    "description": "Umbrella initiative for course-related work within Life Itself.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "courses"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-hubs",
    "type": "initiative",
    "file": "initiatives/life-itself-hubs.md",
    "title": "Life Itself Hubs",
    "description": "Residential conscious communities and hubs within the broader Life Itself ecosystem.",
    "status": "active",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "hubs",
      "community"
    ],
    "url": "https://lifeiteself.org/hubs",
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-management",
    "type": "initiative",
    "file": "initiatives/life-itself-management.md",
    "title": "Life Itself Management",
    "description": "Ongoing management and coordination work for Life Itself.",
    "status": "active",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "management"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-podcast",
    "type": "initiative",
    "file": "initiatives/life-itself-podcast.md",
    "title": "Life Itself Podcast",
    "description": "Podcast initiative under Life Itself.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "podcast"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-practicum",
    "type": "initiative",
    "file": "initiatives/life-itself-practicum.md",
    "title": "Life Itself Practicum",
    "description": "A practicum of service, learning, and community living within Life Itself.",
    "status": "active",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "practicum",
      "learning"
    ],
    "url": "https://news.lifeitself.org/p/life-itself-practicum-autumn-2025",
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself",
    "type": "initiative",
    "file": "initiatives/life-itself.md",
    "title": "Life Itself",
    "description": "Core umbrella project encompassing vision, hubs, research, practice, and digital presence for wiser societies.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": null,
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "microcasts",
    "type": "initiative",
    "file": "initiatives/microcasts.md",
    "title": "Microcasts",
    "description": "Life Itself communications sub-initiative for microcast-style content.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "communications",
      "media"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "over-the-mountains",
    "type": "initiative",
    "file": "initiatives/over-the-mountains.md",
    "title": "Over the Mountains",
    "description": "Blog and podcast exploring civilisational renewal and the emerging Second Renaissance.",
    "status": "active",
    "created": "Sun Mar 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "writing",
      "podcast"
    ],
    "url": "https://overthemountains.substack.com",
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "praxis-ecology",
    "type": "initiative",
    "file": "initiatives/praxis-ecology.md",
    "title": "Praxis Ecology",
    "description": "Initiative for Praxis Ecology learning and course development.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": [
      "lifeitself",
      "course",
      "learning"
    ],
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "second-renaissance",
    "type": "initiative",
    "file": "initiatives/second-renaissance.md",
    "title": "Second Renaissance",
    "description": "Cultural-civilisational renewal project including narrative, events, and movement-building.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "teal-estate",
    "type": "initiative",
    "file": "initiatives/teal-estate.md",
    "title": "Teal Estate",
    "description": "Real-estate strategy and tooling for conscious co-living and community projects.",
    "status": "active",
    "created": "Wed Jan 28 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "developmental-spaces-dds",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2022-11-10-uber-epic-strategy-v3-v4",
    "type": "project",
    "file": "projects/2022-11-10-uber-epic-strategy-v3-v4.md",
    "title": "2022 11 10 Uber Epic Strategy V3 V4",
    "description": null,
    "status": null,
    "created": null,
    "parent": null,
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2026-intro-to-life-itself-videos",
    "type": "project",
    "file": "projects/2026-intro-to-life-itself-videos.md",
    "title": "Intro to Life Itself videos",
    "description": "Introductory video set for Life Itself.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "life-itself",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2026-otm-next-podcast-set",
    "type": "project",
    "file": "projects/2026-otm-next-podcast-set.md",
    "title": "Next Over the Mountains podcast set",
    "description": "Release the next set of Over the Mountains podcasts.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "over-the-mountains",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2026-praxis-ecology-course-v1",
    "type": "project",
    "file": "projects/2026-praxis-ecology-course-v1.md",
    "title": "Praxis Ecology course v1",
    "description": "First version of the Praxis Ecology course by Valerie.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "praxis-ecology",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "2026-second-renaissance-explorer-course-v4",
    "type": "project",
    "file": "projects/2026-second-renaissance-explorer-course-v4.md",
    "title": "Second Renaissance Explorer course v4",
    "description": "Version 4 of the Second Renaissance Explorer course.",
    "status": "active",
    "created": "Mon Mar 30 2026 02:00:00 GMT+0200 (Central European Summer Time)",
    "parent": "second-renaissance",
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  },
  {
    "slug": "life-itself-websites-2025",
    "type": "project",
    "file": "projects/life-itself-websites-2025.md",
    "title": "Life Itself Websites 2025",
    "description": "Major refactor of Life Itself websites to reflect the new strategy and direction.",
    "status": "active",
    "created": "Thu Jan 29 2026 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": "life-itself-management",
    "tags": null,
    "url": "https://lifeitself.org/",
    "github": "https://github.com/life-itself/next.lifeitself.org",
    "phase": "shipping",
    "tracker": "https://github.com/life-itself/next.lifeitself.org/issues"
  },
  {
    "slug": "project-202401-presenting-our-strategy-v3-in-its-current-form",
    "type": "project",
    "file": "projects/project-202401-presenting-our-strategy-v3-in-its-current-form.md",
    "title": "Project 202401 Presenting Our Strategy V3 In Its Current Form",
    "description": null,
    "status": null,
    "created": "Tue Jan 09 2024 01:00:00 GMT+0100 (Central European Standard Time)",
    "parent": null,
    "tags": null,
    "url": null,
    "github": null,
    "phase": null,
    "tracker": null
  }
];
